version: '3.1'

services:

  borsa:
    image: emieza/borsa:v2.1
    restart: always
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=mysqlgis://exampleuser:lapass123@db/exampledb
      - DEBUG=True
      - SECRET_KEY=asecretkey
      # hostnames en produccio, separats per espais
      - ALLOWED_HOSTS=localhost borsa.ieti.cat
      # social auth
      #- SOCIAL_AUTH_GOOGLE_OAUTH2_KEY=akey
      #- SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET=asecret
      # email conf
      #- EMAIL_HOST=smtp.gmail.com
      #- EMAIL_PORT=587
      #- EMAIL_FROM_NAME=Borsa de Treball IETI
      #- EMAIL_HOST_USER=noreply@iesesteveterradas.cat
      #- EMAIL_HOST_PASSWORD=lapass
      #- EMAIL_USE_TLS=True
      #- EMAIL_USE_SSL=False
    volumes:
      - borsa:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: lapass123
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql


volumes:
  borsa:
  db:
