# Generated by Django 2.1.7 on 2019-03-13 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('descripcio', models.TextField(blank=True, null=True)),
                ('pare', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='borsApp.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('direccio', models.TextField()),
                ('poblacio', models.CharField(max_length=255)),
                ('cp', models.CharField(max_length=5)),
                ('telefon', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('web', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Cicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('especialitzacio', models.CharField(max_length=255)),
                ('pladestudis', models.URLField(blank=True, null=True)),
                ('descripcio', models.TextField()),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borsApp.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Demandes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
