# Generated by Django 2.1.10 on 2019-07-21 18:47

from django.db import migrations, models
import django.utils.timezone
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demandes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inici', models.DateTimeField(default=django.utils.timezone.now)),
                ('final', models.DateTimeField()),
                ('activa', models.BooleanField(default=True)),
                ('titol', models.CharField(max_length=255)),
                ('descripcio', djrichtextfield.models.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'Ofertes',
            },
        ),
        migrations.CreateModel(
            name='Subscripcio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia', models.FloatField(default=0.0, help_text='Si la distància és 0 no es tindrà en compte aquest paràmetre')),
                ('creat', models.DateTimeField(auto_now_add=True)),
                ('modificat', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Subscripcions',
            },
        ),
        migrations.CreateModel(
            name='Titol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduat', models.BooleanField()),
                ('data', models.DateField(blank=True, help_text="Data de graduació de l'alumne", null=True)),
                ('descripcio', djrichtextfield.models.RichTextField(blank=True)),
            ],
        ),
    ]
