# Generated by Django 2.1.7 on 2019-03-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cicle',
            name='especialitzacio',
        ),
        migrations.AddField(
            model_name='cicle',
            name='codi',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cicle',
            name='grau',
            field=models.CharField(choices=[('CFGM', 'Grau Mitjà'), ('CFGS', 'Grau Superior')], default='CFGM', max_length=4),
            preserve_default=False,
        ),
    ]
