# Generated by Django 2.1.7 on 2019-04-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='categoria',
            field=models.ManyToManyField(to='borsApp.Categoria'),
        ),
        migrations.AlterField(
            model_name='user',
            name='arxiu',
            field=models.FileField(blank=True, upload_to='docPerfil'),
        ),
        migrations.AlterField(
            model_name='user',
            name='imatge',
            field=models.ImageField(blank=True, upload_to='imatgesPerfil'),
        ),
    ]
