# Generated by Django 2.1.7 on 2019-04-23 18:04

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('borsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descripcio',
            field=djrichtextfield.models.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centre',
            name='direccio',
            field=djrichtextfield.models.RichTextField(),
        ),
        migrations.AlterField(
            model_name='cicle',
            name='descripcio',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
