# Generated by Django 2.1.7 on 2019-06-22 10:33

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('borsApp', '0002_auto_20190423_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='categoria',
        ),
        migrations.AddField(
            model_name='centre',
            name='admins',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='centre',
            name='descripcio',
            field=djrichtextfield.models.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cicles',
            field=models.ManyToManyField(blank=True, to='borsApp.Cicle'),
        ),
        migrations.AddField(
            model_name='user',
            name='localitzacio',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0, 0), null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='centre',
            name='localitzacio',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default=django.contrib.gis.geos.point.Point(2.6875, 41.56), srid=4326),
        ),
        migrations.AlterField(
            model_name='centre',
            name='web',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='descripcio',
            field=djrichtextfield.models.RichTextField(blank=True, null=True),
        ),
    ]
