# Generated by Django 2.1.7 on 2019-04-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borsApp', '0002_auto_20190408_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imatge',
            field=models.ImageField(blank=True, upload_to='imatgesPerfil', verbose_name='1'),
        ),
    ]
