# Generated by Django 2.1.10 on 2019-08-05 12:03

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190805_1203'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('borsApp', '0002_auto_20190721_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('direccio', djrichtextfield.models.RichTextField()),
                ('poblacio', models.CharField(max_length=255)),
                ('cp', models.CharField(max_length=5)),
                ('telefon', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('web', models.URLField(blank=True)),
                ('localitzacio', django.contrib.gis.db.models.fields.PointField(blank=True, default=django.contrib.gis.geos.point.Point(2.6875, 41.56), srid=4326)),
                ('descripcio', djrichtextfield.models.RichTextField(blank=True)),
                ('imatge', models.ImageField(blank=True, upload_to='imatgesCentre')),
                ('admins', models.ManyToManyField(blank=True, related_name='empreses_admin', to=settings.AUTH_USER_MODEL)),
                ('adscripcio', models.ManyToManyField(blank=True, help_text='Centres educatius als que estan adscrits', related_name='adscrites', to='core.Centre')),
            ],
        ),
        migrations.AlterField(
            model_name='oferta',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='borsApp.Empresa'),
        ),
        migrations.AlterField(
            model_name='subscripcio',
            name='centre_educatiu',
            field=models.ForeignKey(blank=True, help_text='Rebre les ofertes dirigides a aquest centre', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscripcions', to='core.Centre'),
        ),
        migrations.AlterField(
            model_name='subscripcio',
            name='centre_treball',
            field=models.ForeignKey(blank=True, help_text="Rebre les ofertes d'aquesta empresa", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscipcions', to='borsApp.Empresa'),
        ),
    ]
