# Generated by Django 2.1.7 on 2019-03-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borsApp', '0002_auto_20190313_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cicle',
            name='codi',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='cicle',
            name='nom',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
