# Generated by Django 2.1.10 on 2019-08-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borsApp', '0003_auto_20190805_1203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name_plural': 'Empreses'},
        ),
        migrations.AlterField(
            model_name='empresa',
            name='adscripcio',
            field=models.ManyToManyField(blank=True, help_text="Centres educatius als que està adscrita l'empresa. ", related_name='empreses', to='core.Centre'),
        ),
    ]
