# Generated by Django 2.1.7 on 2019-06-24 18:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('borsApp', '0003_auto_20190622_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscripcio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centre_alumne', models.BooleanField()),
                ('centre_empresa', models.BooleanField()),
                ('distancia_empresa', models.FloatField(default=0.0)),
                ('distancia_centre', models.FloatField(default=0.0)),
                ('categories', models.ManyToManyField(blank=True, to='borsApp.Categoria')),
                ('cicles', models.ManyToManyField(to='borsApp.Cicle')),
            ],
        ),
        migrations.CreateModel(
            name='Titol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descripcio', djrichtextfield.models.RichTextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='cicles',
        ),
        migrations.AddField(
            model_name='centre',
            name='adscripcio',
            field=models.ManyToManyField(related_name='_centre_adscripcio_+', to='borsApp.Centre'),
        ),
        migrations.AddField(
            model_name='centre',
            name='cicles',
            field=models.ManyToManyField(blank=True, to='borsApp.Cicle'),
        ),
        migrations.AddField(
            model_name='centre',
            name='educatiu',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='centre',
            name='imatge',
            field=models.ImageField(blank=True, upload_to='imatgesCentre'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='activa',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oferta',
            name='caduca',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 26, 18, 33, 36, 887034, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='oferta',
            name='cicles',
            field=models.ManyToManyField(to='borsApp.Cicle'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='creada',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='oferta',
            name='descripcio',
            field=djrichtextfield.models.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oferta',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='borsApp.Centre'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='titol',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='centre',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='titol',
            name='alumne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='titol',
            name='centre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='borsApp.Centre'),
        ),
        migrations.AddField(
            model_name='titol',
            name='cicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='borsApp.Cicle'),
        ),
    ]
