# Generated by Django 2.1.7 on 2019-03-19 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('borsApp', '0004_auto_20190315_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='pare',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='borsApp.Categoria'),
        ),
    ]
