# Generated by Django 2.1.7 on 2019-06-24 22:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('borsApp', '0004_auto_20190624_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscripcio',
            name='alumne',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='centre',
            name='adscripcio',
            field=models.ManyToManyField(blank=True, related_name='_centre_adscripcio_+', to='borsApp.Centre'),
        ),
        migrations.AlterField(
            model_name='centre',
            name='educatiu',
            field=models.BooleanField(help_text='Si no és centre educatiu, és centre de treball.'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='caduca',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 26, 22, 16, 19, 43551, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='titol',
            name='data',
            field=models.DateField(help_text="Data de graduació de l'alumne"),
        ),
    ]
