# Generated by Django 2.1.10 on 2019-08-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borsApp', '0004_auto_20190806_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nom',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
