# Generated by Django 2.1.7 on 2019-04-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borsApp', '0004_auto_20190409_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='descripcio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
