# Generated by Django 2.1.10 on 2019-08-07 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('borsApp', '0005_auto_20190806_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('registre', models.TextField(blank=True)),
                ('enviament', models.DateTimeField(blank=True, null=True)),
                ('confirmacio', models.DateTimeField(blank=True, null=True)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borsApp.Oferta')),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
