# Generated by Django 2.1.7 on 2019-03-19 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('borsApp', '0005_auto_20190319_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cicle',
            name='familia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='borsApp.Categoria'),
        ),
    ]
