# Generated by Django 2.1.7 on 2019-06-24 23:06

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('borsApp', '0005_auto_20190624_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oferta',
            old_name='creada',
            new_name='inici',
        ),
        migrations.RenameField(
            model_name='subscripcio',
            old_name='distancia_centre',
            new_name='distancia',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='caduca',
        ),
        migrations.RemoveField(
            model_name='subscripcio',
            name='centre_alumne',
        ),
        migrations.RemoveField(
            model_name='subscripcio',
            name='centre_empresa',
        ),
        migrations.RemoveField(
            model_name='subscripcio',
            name='distancia_empresa',
        ),
        migrations.AddField(
            model_name='oferta',
            name='final',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 26, 23, 5, 52, 129224, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='subscripcio',
            name='centre',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='borsApp.Centre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscripcio',
            name='creat',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscripcio',
            name='modificat',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
