# Generated by Django 2.1.7 on 2019-03-22 18:17

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borsApp', '0006_auto_20190319_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='centre',
            name='localitzacio',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0, 0), srid=4326),
        ),
    ]
