# Generated by Django 2.1.7 on 2019-06-24 23:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('borsApp', '0006_auto_20190624_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='final',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 26, 23, 9, 10, 6696, tzinfo=utc)),
        ),
    ]
