# Generated by Django 2.1.10 on 2019-08-07 11:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('borsApp', '0006_notificacio'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notificacio',
            unique_together={('oferta', 'usuari')},
        ),
    ]
