# Generated by Django 2.1.10 on 2019-08-13 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borsApp', '0007_auto_20190807_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacio',
            options={'verbose_name_plural': 'Notificacions'},
        ),
    ]
