# Generated by Django 2.1.7 on 2019-06-25 00:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('borsApp', '0008_auto_20190625_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='final',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 27, 0, 12, 58, 271370, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subscripcio',
            name='centre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='borsApp.Centre'),
        ),
    ]
