# Generated by Django 2.1.10 on 2019-08-20 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borsApp', '0009_remove_notificacio_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Demandes',
            new_name='Demanda',
        ),
    ]
