# Generated by Django 2.1.7 on 2019-06-25 13:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('borsApp', '0010_auto_20190625_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='final',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 27, 13, 56, 37, 985511, tzinfo=utc)),
        ),
    ]
