# Generated by Django 2.1.7 on 2019-06-25 18:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('borsApp', '0011_auto_20190625_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='pare',
        ),
        migrations.RemoveField(
            model_name='centre',
            name='admins',
        ),
        migrations.RemoveField(
            model_name='centre',
            name='adscripcio',
        ),
        migrations.RemoveField(
            model_name='centre',
            name='cicles',
        ),
        migrations.RemoveField(
            model_name='cicle',
            name='familia',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='oferta',
            name='cicles',
            field=models.ManyToManyField(to='core.Cicle'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Centre'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='final',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 27, 18, 16, 5, 429225, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subscripcio',
            name='categories',
            field=models.ManyToManyField(blank=True, to='core.Categoria'),
        ),
        migrations.AlterField(
            model_name='subscripcio',
            name='centre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Centre'),
        ),
        migrations.AlterField(
            model_name='subscripcio',
            name='cicles',
            field=models.ManyToManyField(to='core.Cicle'),
        ),
        migrations.AlterField(
            model_name='titol',
            name='centre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Centre'),
        ),
        migrations.AlterField(
            model_name='titol',
            name='cicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Cicle'),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Centre',
        ),
        migrations.DeleteModel(
            name='Cicle',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
