# Generated by Django 2.1.7 on 2019-06-25 23:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('borsApp', '0012_auto_20190625_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='final',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 27, 23, 2, 59, 64718, tzinfo=utc)),
        ),
    ]
