# Generated by Django 2.1.7 on 2019-06-25 23:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('borsApp', '0013_auto_20190625_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='final',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 27, 23, 31, 35, 708430, tzinfo=utc)),
        ),
    ]
