# Generated by Django 2.1.7 on 2019-06-26 08:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('borsApp', '0015_auto_20190626_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='final',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 28, 8, 59, 31, 914149, tzinfo=utc)),
        ),
    ]
