# Generated by Django 2.1.7 on 2019-06-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borsApp', '0017_auto_20190626_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='final',
            field=models.DateTimeField(),
        ),
    ]
