# Generated by Django 2.1.7 on 2019-07-02 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borsApp', '0019_auto_20190628_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='titol',
            name='graduat',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='titol',
            name='data',
            field=models.DateField(blank=True, help_text="Data de graduació de l'alumne", null=True),
        ),
    ]
