# Generated by Django 2.1.7 on 2019-07-04 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('borsApp', '0020_auto_20190702_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titol',
            name='alumne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titols', to=settings.AUTH_USER_MODEL),
        ),
    ]
