# Generated by Django 2.1.10 on 2019-07-11 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190704_2014'),
        ('borsApp', '0021_auto_20190704_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscripcio',
            name='centre',
        ),
        migrations.AddField(
            model_name='subscripcio',
            name='centre_educatiu',
            field=models.ForeignKey(help_text='Rebre les ofertes dirigides a aquest centre', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscripcions_educatiu', to='core.Centre'),
        ),
        migrations.AddField(
            model_name='subscripcio',
            name='centre_treball',
            field=models.ForeignKey(help_text="Rebre les ofertes d'aquesta empresa", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscipcions_treball', to='core.Centre'),
        ),
        migrations.AlterField(
            model_name='subscripcio',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Rebre les ofertes que estiguin en aquestes categories', to='core.Categoria'),
        ),
        migrations.AlterField(
            model_name='subscripcio',
            name='cicles',
            field=models.ManyToManyField(help_text='Rebre les ofertes relacionades amb aquests cicles', to='core.Cicle'),
        ),
        migrations.AlterField(
            model_name='subscripcio',
            name='distancia',
            field=models.FloatField(default=0.0, help_text='Si la distància és 0 no es tindrà en compte aquest paràmetre'),
        ),
    ]
