# Generated by Django 2.1.10 on 2019-07-12 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('borsApp', '0022_auto_20190711_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscripcio',
            name='centre_educatiu',
            field=models.ForeignKey(blank=True, help_text='Rebre les ofertes dirigides a aquest centre', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscripcions_educatiu', to='core.Centre'),
        ),
        migrations.AlterField(
            model_name='subscripcio',
            name='centre_treball',
            field=models.ForeignKey(blank=True, help_text="Rebre les ofertes d'aquesta empresa", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscipcions_treball', to='core.Centre'),
        ),
    ]
