# Generated by Django 2.1.7 on 2019-06-28 00:00

from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModulProfessional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=0)),
                ('nom', models.CharField(max_length=255)),
                ('descripcio', djrichtextfield.models.RichTextField()),
                ('cicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Cicle')),
            ],
        ),
        migrations.CreateModel(
            name='UnitatFormativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=0)),
                ('nom', models.CharField(max_length=255)),
                ('descripcio', djrichtextfield.models.RichTextField()),
                ('mp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ModulProfessional')),
            ],
        ),
    ]
