# Generated by Django 2.1.10 on 2019-07-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centre',
            name='cicles',
            field=models.ManyToManyField(blank=True, related_name='centres', to='core.Cicle'),
        ),
    ]
