# Generated by Django 2.1.10 on 2019-08-05 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190724_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centre',
            name='adscripcio',
        ),
        migrations.RemoveField(
            model_name='centre',
            name='educatiu',
        ),
    ]
