# Generated by Django 2.1.7 on 2019-06-28 21:57

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_modulprofessional_unitatformativa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='modulprofessional',
            options={'verbose_name_plural': 'Moduls Professionals'},
        ),
        migrations.AlterModelOptions(
            name='unitatformativa',
            options={'verbose_name_plural': 'Unitats Formatives'},
        ),
        migrations.AlterField(
            model_name='modulprofessional',
            name='descripcio',
            field=djrichtextfield.models.RichTextField(blank=True),
        ),
    ]
