# Generated by Django 2.1.7 on 2019-07-04 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190702_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='centre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Centre'),
        ),
        migrations.AlterField(
            model_name='centre',
            name='adscripcio',
            field=models.ManyToManyField(blank=True, related_name='adscrits', to='core.Centre'),
        ),
    ]
