# Generated by Django 2.1.10 on 2019-07-21 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190704_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='arxiu',
            field=models.FileField(blank=True, help_text='Carrega aquí el CV', upload_to='docPerfil'),
        ),
        migrations.AlterField(
            model_name='user',
            name='centre',
            field=models.ForeignKey(blank=True, help_text="Centre on està actualment matriculat l'alumne o el darrer centre on hi va estar.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Centre'),
        ),
        migrations.AlterField(
            model_name='user',
            name='imatge',
            field=models.ImageField(blank=True, help_text='Carrega aquí la teva imatge.', upload_to='imatgesPerfil'),
        ),
    ]
