# Generated by Django 2.2.4 on 2020-01-20 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dual', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demandadual',
            options={'verbose_name_plural': 'DemandesDual'},
        ),
    ]
