# Generated by Django 2.1.7 on 2019-06-25 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0002_spec_mp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spec',
            name='mp',
        ),
        migrations.AddField(
            model_name='spec',
            name='mp',
            field=models.ManyToManyField(blank=True, help_text='Mòdul Professional', to='scrum.ModulProfessional'),
        ),
        migrations.AlterField(
            model_name='spec',
            name='pare',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrum.Spec'),
        ),
    ]
