# Generated by Django 2.1.7 on 2019-06-26 08:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scrum', '0003_auto_20190625_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='equip',
            name='membres',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
