# Generated by Django 2.1.7 on 2019-06-26 21:32

import datetime
from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0004_equip_membres'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='final',
            field=models.DateField(default=datetime.datetime(2019, 7, 3, 21, 32, 29, 531934)),
        ),
        migrations.AddField(
            model_name='sprint',
            name='inici',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='projecte',
            name='final',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='projecte',
            name='inici',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='notes',
            field=djrichtextfield.models.RichTextField(blank=True),
        ),
    ]
