# Generated by Django 2.1.7 on 2019-06-28 21:57

from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190628_2157'),
        ('scrum', '0006_auto_20190628_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecte',
            name='cicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Cicle'),
        ),
        migrations.AlterField(
            model_name='equip',
            name='descripcio',
            field=djrichtextfield.models.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='spec',
            name='descripcio',
            field=djrichtextfield.models.RichTextField(blank=True),
        ),
    ]
