# Generated by Django 2.1.7 on 2019-06-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0007_auto_20190628_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='specs',
            field=models.ManyToManyField(blank=True, help_text='Especificacions que entren en aquest sprint', to='scrum.Spec'),
        ),
        migrations.AlterField(
            model_name='spec',
            name='mp',
            field=models.ManyToManyField(blank=True, help_text='Mòduls Professionals', to='core.ModulProfessional'),
        ),
    ]
