# Generated by Django 2.2.13 on 2020-11-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0009_auto_20201006_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spec',
            name='nom',
            field=models.CharField(max_length=600),
        ),
    ]
