# Generated by Django 2.1.7 on 2019-07-01 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0010_qualificacio'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecDone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='qualificacio',
            name='nota',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specdone',
            name='qualificacio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrum.Qualificacio'),
        ),
        migrations.AddField(
            model_name='specdone',
            name='spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrum.Spec'),
        ),
    ]
