# Generated by Django 2.2.13 on 2020-11-26 12:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0011_specfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specfeedback',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='specfeedback',
            name='spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='scrum.Spec'),
        ),
    ]
