# Generated by Django 2.1.7 on 2019-07-01 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0011_auto_20190701_0841'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpecDone',
            new_name='DoneSpec',
        ),
        migrations.AlterModelOptions(
            name='qualificacio',
            options={'verbose_name_plural': 'Qualificacions'},
        ),
    ]
