# Generated by Django 2.1.7 on 2019-07-02 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0012_auto_20190701_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donespec',
            name='qualificacio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='done_specs', to='scrum.Qualificacio'),
        ),
        migrations.AlterField(
            model_name='equip',
            name='projecte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equips', to='scrum.Projecte'),
        ),
    ]
