# Generated by Django 2.2.13 on 2020-12-02 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0013_auto_20201202_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='specfeedback',
            name='equip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='scrum.Equip'),
        ),
        migrations.AlterField(
            model_name='specfeedback',
            name='usuari',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL),
        ),
    ]
