# Generated by Django 2.1.10 on 2019-07-11 11:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0013_auto_20190702_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecte',
            name='admins',
            field=models.ManyToManyField(help_text='Incloure aquí als professors implicats en el projecte', to=settings.AUTH_USER_MODEL),
        ),
    ]
