# Generated by Django 2.2.24 on 2021-10-29 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0014_auto_20201202_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualificacio',
            name='equip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualificacions', to='scrum.Equip'),
        ),
        migrations.AlterField(
            model_name='qualificacio',
            name='sprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualificacions', to='scrum.Sprint'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='projecte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='scrum.Projecte'),
        ),
    ]
