# Generated by Django 2.2.24 on 2021-11-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0015_auto_20211029_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spec',
            name='hores_estimades',
            field=models.FloatField(default=0.0),
        ),
    ]
