# Generated by Django 2.2.24 on 2024-11-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0016_auto_20211112_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='equip',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
