# Generated by Django 2.2.24 on 2022-03-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0016_auto_20211112_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='donespec',
            name='nota',
            field=models.FloatField(default=0.0),
        ),
    ]
