# Generated by Django 2.2.24 on 2022-03-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0017_donespec_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donespec',
            name='done',
            field=models.FloatField(default=0.0),
        ),
    ]
